name: 'Updates a Quickbase solution'
description: 'Updates a Quickbase solution when PR is merged'
author: 'ekaradzha@quickbase.com'

# Define your inputs here.
inputs:
  gh_token:
    description: 'GitHub token'
    required: true
  # QBL settings
  qb_user_token:
    description: 'Quickbase user token'
    required: true
  qb_realm:
    description: 'Quickbase realm name'
    required: true
  qbl_version:
    description: 'Quickbase QBL version'
    default: '0.2'
  qbl_filename:
    description:
      'Filename for the QBL file the will be checked in the repository'
    default: 'solution_qbl.yaml'
  qb_solution_id_to_update:
    description: 'ID of solution to be updated'
    required: true

# Define your outputs here.
outputs:
  solution_api_message:
    description: 'Messages returned from Solution API'

runs:
  using: node20
  main: dist/index.js
